
service: kela-chatbot-serverless
# app and org for use with dashboard.serverless.com
app: kela-chatbot-serverless
org: samulirukkila

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1

plugins:
  - serverless-ignore
  - serverless-plugin-typescript

# you can add statements to the Lambda function's IAM Role here
iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - cloudwatch:*

functions:

  # Get user's Kela information
  KelaUserInformation:
    handler: lambdas/userInformation/userInformation.handler
    name: kela-userInformation
    description: Gets user information from DynamoDB via provided PIN
    
  # Book a new time for Kela meeting
  KelaBookAppointment:
    handler: lambdas/bookAppointment/bookAppointment.handler
    name: kela-bookAppointment
    description: Books an appointment for the user 

  # Locate nearest Kela -apartment
  KelaLocateNearestBuilding:
    handler: lambdas/locateNearestBuilding/locateNearestBuilding.handler
    name: kela-locateNearestBuilding


resources:
  Resources:
    # DynamoDB table for Customer-data
    KelaCustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: kela-Customers
        AttributeDefinitions:
          - AttributeName: Pin
            AttributeType: S
        KeySchema:
          - AttributeName: Pin
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    # DynamoDB table for booked appointments
    KelaAppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: kela-Appointments
        AttributeDefinitions:
          - AttributeName: StartDateTime
            AttributeType: S
          - AttributeName: EndDateTime
            AttributeType: S
        KeySchema:
          - AttributeName: StartDateTime
            KeyType: HASH
          - AttributeName: EndDateTime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
